### ISSUE TITLE
Assess token not cached

### ISSUE THREAD

**Issue by barmyscotsman** [mattfeltonma/python-b2c-sample#5]
Hi Matt, Thanks for the tutorial but I am trying to get it working. When I click on MyAccount tab, the cache token response seems to be missing the assess token. I tried this tutorial twice but unable to solve the assess token. Any ideas? 

Cheers Paul

**Comment by barmyscotsman** [comment]
I'm going to try this example.

https://github.com/Azure-Samples/ms-identity-python-on-behalf-of

**Comment by mattfeltonma** [comment]
Hi Paul.

I'm buried this week, but I can certainly take a look at this when I get back from vacation. Which deployment model did you use? Option 1 or Option 2?

**Comment by mattfeltonma** [comment]
Where are you expecting the access tokens to be returned to? Are you unable to authenticate and log into the account? I'm trying to understand exactly where you want the access token to be returned to in order to validate that the behavior you expect is the behavior the app is performing.

Thanks!

**Comment by barmyscotsman** [comment]
In the blog when you click on the tab for the account details, I dont get the screen. I don't hav3 an access token as it throws an error.

**Comment by mattfeltonma** [comment]
One thing I didn’t do well in the code was report back errors. It could be an error with your B2C configuration. If you’re comfortable with Python, id modify the code where the access token is called to log the result of the call.

When I get a chance I can check it myself.
________________________________

**Comment by barmyscotsman** [comment]
`# Retrieve an ID token and access token for the user and store the ID token claims in the server-side session
# Place the access token and id token into cache
def retrieve_id_token(code, scopes, redirect_uri, authority):
    cache = _load_cache()
    print(cache)
    print(authority)
    result = _build_msal_app(authority=authority, cache=cache).acquire_token_by_authorization_code(
        request.args['code'],
        scopes=scopes,
        redirect_uri=redirect_uri)
    if "error" in result:
        return result
    if not session.get('user'):
        session["user"] = result.get("id_token_claims")
    _save_cache(cache)
`

I have already added a print statement when debugging the access token. I assumed something is missing in my setup of b2c.

**Comment by mattfeltonma** [comment]
Your print statements are before the token is acquired so it will report as empty. Try moving your print statements to after the _save_cache function runs.

**Comment by barmyscotsman** [comment]
Thanks for your help. I give it another try.

**Comment by mattfeltonma** [comment]
Good deal! I'll try to find time to run through the blog and instructions tomorrow as well to validate I didn't miss a step somewhere. I'll let you know what the results are!
